### ISSUE TITLE
When trying to run either the rematcher or the library import, a 404 error occurs

### ISSUE THREAD

**Issue by banzai200** [gaseous-project/gaseous-server#370]
**Describe the bug**
After trying to run the rematcher on the settings menu, the server logs return the following error

```
20240619 202041: Warning: Timered Event: An error occurred
System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at HasheousClient.WebApp.HttpHelper.Post[T](String url, Object contentValue)
   at HasheousClient.Hasheous._RetrieveFromHasheousAsync(HashLookupModel hashLookup)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at HasheousClient.Hasheous.RetrieveFromHasheousAsync(HashLookupModel hash)
   at gaseous_server.Classes.FileSignature._GetFileSignatureFromHasheous(hashObject hash, String ImageName, String ImageExtension, Int64 ImageSize, String GameFileImportPath) in /App/gaseous-server/Classes/FileSignature.cs:line 267
   at gaseous_server.Classes.FileSignature._GetFileSignature(hashObject hash, String ImageName, String ImageExtension, Int64 ImageSize, String GameFileImportPath, Boolean IsInZip) in /App/gaseous-server/Classes/FileSignature.cs:line 192
   at gaseous_server.Classes.FileSignature.GetFileSignature(LibraryItem library, hashObject hash, FileInfo fi, String GameFileImportPath) in /App/gaseous-server/Classes/FileSignature.cs:line 19
   at gaseous_server.Classes.ImportGame.Rematcher(Boolean ForceExecute) in /App/gaseous-server/Classes/ImportGames.cs:line 768
   at gaseous_server.ProcessQueue.QueueItem.Execute() in /App/gaseous-server/ProcessQueue.cs:line 329
```
i've been trying to use the rematcher and the metadata refresh several times to organize the files to the right place

**Comment by michael-j-green** [comment]
This is an error that can be safely ignored. It's the Hasheous service (IGDB does the same) simply reporting that search did not succeed.

I've added this to the 1.8.0 milestone as needing improvement around logging to make it clear what's going on.

**Comment by michael-j-green** [comment]
Resolved in v2.0
